# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='board_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_text_zh_hans',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_text_zh_hant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_title_zh_hans',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='board_title_zh_hant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
