# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170926_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='search_description_en',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='search_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='search_description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='seo_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='seo_title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='slug_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='slug_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='url_path_en',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='url_path_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='url_path_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='search_description_en',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='search_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='search_description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='seo_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='seo_title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='slug_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='slug_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='url_path_en',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='url_path_zh_hans',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='url_path_zh_hant',
        ),
    ]
