# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=500)),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', '简体中文'), ('zh-hant', '繁體中文')], max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
