# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0002_auto_20170918_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jumbotron',
        ),
        migrations.AddField(
            model_name='homepage',
            name='jumbotron_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
