# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170920_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='brand_intro',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing Brand', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_intro_en',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing Brand', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_intro_zh_hans',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing Brand', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_intro_zh_hant',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing Brand', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='jumbotron_image',
            field=models.ForeignKey(blank=True, help_text='Background image for home jumbotron', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='liqueur_intro',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing liqueur', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='liqueur_intro_en',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing liqueur', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='liqueur_intro_zh_hans',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing liqueur', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='liqueur_intro_zh_hant',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Introduction for Jing liqueur', null=True),
        ),
    ]
