# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20170925_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='CustomPage',
        ),
    ]
