# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170926_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='search_description_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='search_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='search_description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='seo_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='seo_title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='slug_zh_hans',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='slug_zh_hant',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='url_path_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='url_path_zh_hans',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='url_path_zh_hant',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_description_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slug_zh_hans',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slug_zh_hant',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_path_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_path_zh_hans',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_path_zh_hant',
        ),
    ]
