# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 08:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170920_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brand_intro',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brand_intro_en',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brand_intro_zh_hans',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brand_intro_zh_hant',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='liqueur_intro',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='liqueur_intro_en',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='liqueur_intro_zh_hans',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='liqueur_intro_zh_hant',
            field=wagtail.wagtailcore.fields.RichTextField(null=True),
        ),
    ]
