# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170920_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jumbotron_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='jumbotrons',
            field=wagtail.wagtailcore.fields.StreamField((('jumbotron', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Background image for home jumbotron')), ('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron title', max_length=120, null=True)), ('body', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron body', max_length=120, null=True))))),), help_text='Home jumbotron', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='jumbotrons_en',
            field=wagtail.wagtailcore.fields.StreamField((('jumbotron', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Background image for home jumbotron')), ('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron title', max_length=120, null=True)), ('body', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron body', max_length=120, null=True))))),), help_text='Home jumbotron', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='jumbotrons_zh_hans',
            field=wagtail.wagtailcore.fields.StreamField((('jumbotron', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Background image for home jumbotron')), ('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron title', max_length=120, null=True)), ('body', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron body', max_length=120, null=True))))),), help_text='Home jumbotron', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='jumbotrons_zh_hant',
            field=wagtail.wagtailcore.fields.StreamField((('jumbotron', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Background image for home jumbotron')), ('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron title', max_length=120, null=True)), ('body', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='Home jumbotron body', max_length=120, null=True))))),), help_text='Home jumbotron', null=True),
        ),
    ]
